# Generated by Django 5.0.6 on 2024-09-11 17:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CreditSale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('buyer_name', models.CharField(max_length=100)),
                ('branch', models.CharField(max_length=14, null=True)),
                ('location', models.CharField(max_length=100, null=True)),
                ('contact', models.CharField(max_length=15, null=True)),
                ('amount_due', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('sales_agent_name', models.CharField(max_length=100)),
                ('due_date', models.DateField(auto_now_add=True)),
                ('product_name', models.CharField(max_length=100, null=True)),
                ('tonnage', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date_of_dispatch', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=255, null=True)),
                ('total_quantity', models.PositiveIntegerField()),
                ('unit_cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='stockx',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(blank=True, max_length=50, null=True)),
                ('stock_source', models.CharField(blank=True, max_length=50, null=True)),
                ('total_price', models.DecimalField(blank=True, decimal_places=2, default=15.0, max_digits=10)),
                ('unit_cost', models.DecimalField(blank=True, decimal_places=2, default=10.0, max_digits=10)),
                ('stock_branch', models.CharField(blank=True, max_length=50, null=True)),
                ('total_quantity', models.IntegerField(blank=True, default=0, null=True)),
                ('issued_quantity', models.IntegerField(blank=True, default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(blank=True)),
                ('amount_received', models.DecimalField(blank=True, decimal_places=2, max_digits=10)),
                ('issued_to', models.CharField(blank=True, max_length=50, null=True)),
                ('unitcost', models.DecimalField(blank=True, decimal_places=2, max_digits=10)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='groceryapp.stockx')),
            ],
        ),
    ]
