# Generated by Django 5.0.6 on 2024-09-12 04:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('groceryapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='unit_price',
            new_name='total_price',
        ),
    ]
