# Generated by Django 5.0.6 on 2024-09-12 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groceryapp', '0003_alter_product_total_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockx',
            name='total_price',
            field=models.DecimalField(blank=True, decimal_places=2, default=15.0, max_digits=10, null=True),
        ),
    ]
